services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-17-bookworm
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - mongo
    env_file:
      - path: .env
        required: false

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
